In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
)
from sklearn.preprocessing import StandardScaler

In [2]:
df=pd.read_csv(r"C:\Users\M.Nikhileswara\OneDrive\Desktop\Machine Learning\credit card fraud detection\creditcard.csv")

In [3]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [4]:
df=df.drop(['Time'],axis=1)

In [5]:
df.shape

(284807, 30)

In [6]:
df['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [7]:
df.head()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,0.090794,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,-0.166974,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,0.207643,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,-0.054952,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,0.753074,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [8]:
df.isnull().sum()

V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [9]:
df.duplicated().any()

np.True_

In [10]:
df=df.drop_duplicates()

In [11]:
df.shape

(275663, 30)

In [12]:
df['Class'].value_counts()

Class
0    275190
1       473
Name: count, dtype: int64

In [13]:
X=df.drop(['Class'],axis=1)
y=df['Class']

In [14]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [15]:
scaler=StandardScaler()
X_trainlr=scaler.fit_transform(X_train)
X_testlr=scaler.transform(X_test)

In [16]:
lrmodel=LogisticRegression()
lrmodel.fit(X_trainlr,y_train)

LogisticRegression()

In [17]:
y_predlr=lrmodel.predict(X_testlr)

In [18]:
print("test accuracy: ",accuracy_score(y_test,y_predlr))
print("precision : ",precision_score(y_test,y_predlr))
print("recall : ",recall_score(y_test,y_predlr))
print("f1 score: ",f1_score(y_test,y_predlr))
print("confusion matrix:\n",confusion_matrix(y_test,y_predlr))

test accuracy:  0.9990568262202311
precision :  0.8472222222222222
recall :  0.5980392156862745
f1 score:  0.7011494252873564
confusion matrix:
 [[55020    11]
 [   41    61]]

### Balanced Model but recall is Low

## Oversampling

In [19]:
from imblearn.over_sampling import SMOTE

In [20]:
smote=SMOTE()

In [21]:
X_over_train,y_over_train = smote.fit_resample(
    X_trainlr,
    y_train)

In [22]:
X_over_train.shape

(440318, 29)

In [23]:
y_train.value_counts()

Class
0    220159
1       371
Name: count, dtype: int64

In [24]:
y_over_train.value_counts()

Class
0    220159
1    220159
Name: count, dtype: int64

In [25]:
lrmodel.fit(X_over_train,y_over_train)

LogisticRegression()

In [26]:
y_over_pred=lrmodel.predict(X_testlr)

In [27]:
print("test accuracy: ",accuracy_score(y_test,y_over_pred))
print("precision : ",precision_score(y_test,y_over_pred))
print("recall : ",recall_score(y_test,y_over_pred))
print("f1 score: ",f1_score(y_test,y_over_pred))
print("confusion matrix:\n",confusion_matrix(y_test,y_over_pred))

test accuracy:  0.9738269276114124
precision :  0.060903732809430254
recall :  0.9117647058823529
f1 score:  0.1141804788213628
confusion matrix:
 [[53597  1434]
 [    9    93]]

### Very High recall but too many False Positives

## Random Forest

In [28]:
from sklearn.ensemble import RandomForestClassifier

In [29]:
Ranmodel=RandomForestClassifier()

In [32]:
Ranmodel.fit(X_train,y_train)

RandomForestClassifier()

In [33]:
y_predrf=Ranmodel.predict(X_test)
print("test accuracy: ",accuracy_score(y_test,y_predrf))
print("precision : ",precision_score(y_test,y_predrf))
print("recall : ",recall_score(y_test,y_predrf))
print("f1 score: ",f1_score(y_test,y_predrf))
print("confusion matrix:\n",confusion_matrix(y_test,y_predrf))

test accuracy:  0.9995646890247221
precision :  0.9642857142857143
recall :  0.7941176470588235
f1 score:  0.8709677419354839
confusion matrix:
 [[55028     3]
 [   21    81]]

### Best fitted Model